[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "16"

[build]
  publish = "playground/dist"
  command = "npx pnpm i && npx pnpm run build && npx pnpm -C playground/ run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
